# Configure a default setup of Home Assistant (frontend, api, etc)
# https://www.home-assistant.io/integrations/default_config/
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  name: !secret ha_name
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  elevation: !secret my_elevation
  currency: !secret my_currency
  time_zone: !secret my_time_zone
  unit_system: Metric
  # Needed for https://www.home-assistant.io/integrations/google_assistant
  external_url: !secret my_external_url
  internal_url: !secret my_internal_url

http:
  server_port: !secret http_port
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

logger: !include logger.yaml
sensor: !include_dir_merge_list sensor
notify: !include_dir_merge_list notify

wake_on_lan:
media_player:

webostv:
  - name: !secret webos_tv_a_name
    host: !secret webos_tv_a_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webos_tv_a_mac
        broadcast_address: !secret network_mask

  - name: !secret webos_tv_b_name
    host: !secret webos_tv_b_ip
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webos_tv_b_mac
        broadcast_address: !secret network_mask
